### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ClearlyElevated** [PredaaA/predacogs#12]
Any intrest in making an API cog for my bot site? I tried but with many trial and error i gave up. I am just starting out with Js so looking at py wasnt even beginning to make sense. Anyway. here is the ur. https://discordhouse.org 

there is a few red bots listed already.

**Comment by PredaaA** [comment]
@ClearlyElevated I'm going to DM you on Discord to discuss about that. I'm not sure what you exactly want + I'm not sure if I have the time to do it.
