### ISSUE TITLE
grafana — resolver not driving to proper display coordinates

### ISSUE THREAD

**Issue by kablekompany** [PredaaA/predacogs#47]
After normal setup, the imported panels are as follows (with SS from the web UI)
```python
server_growth, discord_latency, discord_gateway, and panel_17
```
> This is from my web browser 
> ![image](https://kableko.s3-us-east-2.amazonaws.com/skyjacked-petrotympanic-weekwam-ventriculites.png)

However, when trying to pull in the panel ID from invocation of `[p]graph <panel_id>` I get the following:
> ![image](https://kableko.s3-us-east-2.amazonaws.com/francas-noncontemptibility-distr-provident.png)
> Note the second image will show on any other panel the same way. These are the only two outputs I am able to retrieve regardless the panel_id that is passed. 

Let me know if you need anymore details fam <3

**Comment by PredaaA** [comment]
Sorry I'm responding this late but, seems like custom css is breaking the renderer, so it's more like an grafana renderer issue.
