### ISSUE TITLE
converters: Kelvin to Celsius conversion is swapped with Fahrenheit 

### ISSUE THREAD

**Issue by synrg** [PredaaA/predacogs#59]
The Kelvin to Celcius conversion is returning the Fahrenheit result, and the Kelvin to Fahrenheit conversion is returning the Celsius result. Please swap them so they calculate the values for the correct output unit.

![image](https://user-images.githubusercontent.com/1204376/112479136-7fbfa480-8d53-11eb-8255-cc374f0465cc.png)

The inverse operations are correct (i.e. Kelvin to Celsius or Fahrenheit).

**Comment by PredaaA** [comment]
Fixed in latest commit, thanks for your report. 😄
