### ISSUE TITLE
Nsfw rate limit

### ISSUE THREAD

**Issue by mon5termatt** [PredaaA/predacogs#68]
I saw that it has been fixed in martine bot so I'm assuming the same fix can be applied here?

**Comment by PredaaA** [comment]
No the "same fix" cannot be applied here, because Martine use something totally different that's built for the bot specifically.

However it is planned that a fix will come to my cogs which are fetching images from Reddit API. But no ETA.

**Comment by mon5termatt** [comment]
Good enough for me. I know you don't get paid to do this so take your time. Thanks for the update!

**Comment by PredaaA** [comment]
Fixed since https://github.com/PredaaA/predacogs/commit/553cef266687561e0d599e04e774300add688bfc
