### ISSUE TITLE
[RandImages] some-random-api.ml is now some-random-api.com

### ISSUE THREAD

**Issue by michaelnguyenm** [PredaaA/predacogs#79]
When using commands that retrieve facts from `some-random-api.ml` such as [p]catfact or [p]dogfact or [p]pandafact or images for commands such as [p]panda and [p]pika, a JSON decode error occurs. This is because the domain is now `some-random-api.com`

![image](https://github.com/PredaaA/predacogs/assets/8785414/a8b3cdd5-6419-4a1b-a2b6-ee0d8455c18b)

**Comment by BenCos17** [comment]
Fixed in #83
