### ISSUE TITLE
Images from Redgifs no longer working

### ISSUE THREAD

**Issue by DanasaurUK** [PredaaA/predacogs#80]
It looks like due to backend changes on redgifs, https://i.redgifs.com embeds no longer work, is there a way for these to be removed/disabled/filtered out?

**Comment by PredaaA** [comment]
Hi, thanks for the report. I've just fixed that on the API side, it should now return the correct link for redgifs images.

**Comment by DanasaurUK** [comment]
Sorry I forgot to mention I am using the martine API, Redgifs appears to be working with a static thumbnail, not a gif anymore, but the reddit.com source gifs/videos are not working

**Comment by PredaaA** [comment]
Yes, I have fixed it on Martine API side. Now it will return a link as the following: `https://www.redgifs.com/watch/IMAGE_ID` which displays as a embed which contains the image or the gif, gifs are just videos instead on those.
As for the reddit source, it's not going to work so I have made it ignore the redgifs urls if it's the one selected.

**Comment by DanasaurUK** [comment]
Thank you for foing that, but now the Martine API does not work with htps://reddit.com posts

**Comment by PredaaA** [comment]
Hmm can you explain what's happening exactly? I'm seeing it working with all the commands.

**Comment by DanasaurUK** [comment]
Attached is a screenshot of what I see when the cog attempts to embed an image from a http://reddit.com post, the media link is https://www.reddit.com/r/BustyPetite/comments/13bltcd/they_taste_as_nice_as_they_look/

It appears as though the cog is retrieving the post URL rather than the image/gif/video url

![Screenshot_2023-05-11-15-59-37-78_572064f74bd5f9fa804b05334aa4f912](https://github.com/PredaaA/predacogs/assets/86468015/6c1adac8-cd05-4e25-9753-ae23ca5c9669)

**Comment by PredaaA** [comment]
Ah alright, I've just fixed it, thanks for reporting that too
